@echo off
cd /d C:\Development\workspace\chitrakala_arts
echo Adding files...
git add .
echo Committing...
git commit -m "Fix ESLint errors for Vercel build"
echo Pushing to GitHub...
git push origin main
echo.
echo DONE! Build fixes pushed. Vercel will rebuild. Press any key to close...
pause >nul
