@echo off
cd /d C:\Development\workspace\chitrakala_arts
echo Adding files...
git add .
echo Committing...
git commit -m "Force Vercel webhook trigger"
echo Pushing to GitHub...
git push origin main
echo.
echo DONE! Pushed to GitHub. Check Vercel for new deployment. Press any key to close...
pause >nul
