@echo off
cd /d C:\Development\workspace\chitrakala_arts
echo Adding files...
git add .
echo Committing...
git commit -m "Add About page CMS with admin editor and image upload"
echo Pushing to GitHub...
git push origin main
echo.
echo DONE! About page CMS pushed. Railway and Vercel will deploy. Press any key to close...
pause >nul
